name: CustomEffectsAPI
version: '${project.version}'
main: space.outbreak.customeffects.CustomEffectsAPIPlugin
api-version: 1.16
commands:
  customeffects:
    permission: "outbreak.customeffects.admin"